// Host tests for mod auto-download: SHA-256, CRC-32, DEFLATE, zip reading,
// the verified-mods list and PC's naming rules.
//
// The vectors in mod_download_vectors.inc were made with Python's zlib,
// zipfile and hashlib. The "dynamic" and zip payloads are generated by the
// same LCG as Generate() below, so the test can rebuild them.
//
// Optional arguments: paths to real mod archives (for example a verified
// Thunderstore package). Every entry is inflated and checked against the CRC
// its central directory records.
#include "northstar_ps4/mod_archive.h"
#include "northstar_ps4/mod_download.h"
#include <cassert>
#include <cstdio>
#include <memory>
#include <string>
#include <vector>
using namespace northstar::ps4::mods;

#include "mod_download_vectors.inc"

namespace {
struct MemorySource {
    const unsigned char* data; std::size_t size, at = 0;
    int Next() { return at < size ? data[at++] : -1; }
};
struct StringSink {
    std::string out;
    bool Write(const std::uint8_t* p, std::size_t n) { out.append(reinterpret_cast<const char*>(p), n); return true; }
};
struct CountingSink {
    std::uint64_t bytes = 0;
    bool Write(const std::uint8_t*, std::size_t n) { bytes += n; return true; }
};

std::string Generate(int n) {
    std::uint32_t x = 12345;
    std::string out;
    for (int i = 0; i < n; ++i) {
        x = (x * 1103515245u + 12345u) & 0x7fffffffu;
        out += "acgt"[(x >> 16) & 3];
    }
    return out;
}

template<std::size_t N>
std::string InflateAll(const unsigned char (&data)[N], InflateStatus expected, std::uint32_t* crc = nullptr) {
    MemorySource source{data, N};
    StringSink sink;
    auto inflater = std::make_unique<Inflater<MemorySource, StringSink>>(source, sink);
    assert(inflater->Run() == expected);
    if (crc) *crc = inflater->Crc();
    return sink.out;
}

void TestInflate() {
    std::uint32_t crc = 0;
    assert(InflateAll(k_stored, InflateStatus::Ok, &crc) == "hello stored world");
    assert(crc == k_stored_crc);
    assert(InflateAll(k_fixed, InflateStatus::Ok, &crc) == "abcabcabcabcabcabc hello hello hello");
    assert(crc == k_fixed_crc);
    const std::string base = Generate(3000);
    // Python's gen(500) restarts the LCG, so its output is the first 500 bytes.
    const std::string expected = base + std::string(10, '-') + base + Generate(500) + base;
    const std::string dynamic = InflateAll(k_dynamic, InflateStatus::Ok, &crc);
    assert(dynamic.size() == k_dynamic_size && dynamic == expected && crc == k_dynamic_crc);

    // Truncated input ends cleanly instead of reading past the buffer.
    unsigned char truncated[sizeof(k_dynamic) / 2];
    std::memcpy(truncated, k_dynamic, sizeof(truncated));
    InflateAll(truncated, InflateStatus::InputEnded);
    // Block type 3 is reserved.
    const unsigned char reserved[] = {0x07, 0x00};
    InflateAll(reserved, InflateStatus::BadData);
    // A stored block whose length check fails.
    const unsigned char badStored[] = {0x01, 0x05, 0x00, 0x00, 0x00, 'x'};
    InflateAll(badStored, InflateStatus::BadData);
    // A back-reference before the start of the output (fixed block, length
    // 3 at distance 1 with nothing written): 0x03 = final + fixed, then
    // symbol 257 (7 bits, 0000001) and distance code 0.
    const unsigned char badDistance[] = {0x03, 0x02, 0x00};
    InflateAll(badDistance, InflateStatus::BadData);
    // Output failures stop the decoder.
    struct FailingSink { bool Write(const std::uint8_t*, std::size_t) { return false; } } failing;
    MemorySource source{k_stored, sizeof(k_stored)};
    auto inflater = std::make_unique<Inflater<MemorySource, FailingSink>>(source, failing);
    assert(inflater->Run() == InflateStatus::OutputFailed);
}

void TestHashes() {
    Sha256 sha;
    sha.Update("abc", 3);
    assert(sha.FinishHex() == k_abc_sha);
    sha.Reset();
    const std::string chunk(1000, 'a');
    for (int i = 0; i < 1000; ++i) sha.Update(chunk.data(), chunk.size());
    assert(sha.FinishHex() == k_million_a_sha);
    sha.Reset();
    assert(sha.FinishHex() == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
    assert(Crc32Update(0, reinterpret_cast<const std::uint8_t*>("123456789"), 9) == 0xcbf43926u);
}

void TestZip() {
    const std::size_t size = sizeof(k_zip);
    ZipDirectoryLocation location;
    assert(FindZipDirectory(k_zip, size, size, location));
    assert(location.entries == 4);
    std::vector<ZipEntry> entries;
    assert(ParseZipDirectory(k_zip + location.offset, location.size, location.entries, entries));
    assert(entries.size() == 4 && entries[0].IsDirectory() && entries[1].method == 0 && entries[3].method == 8);
    const std::string base = Generate(3000);
    const std::string payload = base + std::string(10, '-') + base + Generate(500) + base;
    for (const auto& entry : entries) {
        if (entry.IsDirectory()) continue;
        std::uint64_t offset = 0;
        assert(ZipDataOffset(k_zip + entry.localHeaderOffset, entry, offset));
        std::string data;
        if (entry.method == 0) {
            data.assign(reinterpret_cast<const char*>(k_zip + offset), entry.size);
        } else {
            MemorySource source{k_zip + offset, entry.compressedSize};
            StringSink sink;
            auto inflater = std::make_unique<Inflater<MemorySource, StringSink>>(source, sink);
            assert(inflater->Run() == InflateStatus::Ok);
            data = sink.out;
        }
        assert(data.size() == entry.size);
        assert(Crc32Update(0, reinterpret_cast<const std::uint8_t*>(data.data()), data.size()) == entry.crc);
        if (entry.name == "pkg/mods/Test.Mod/mod/data.txt") assert(data == payload);
    }
    // Thunderstore: whole archive, root "".
    assert(ZipInstallPath(entries[0], "").empty());
    assert(ZipInstallPath(entries[2], "") == "pkg/mods/Test.Mod/mod.json");
    // ModWorkshop: relative to the first mod.json's folder, others skipped.
    std::string root;
    assert(FindModWorkshopRoot(entries, root) && root == "pkg/mods/Test.Mod/");
    assert(ZipInstallPath(entries[1], root).empty());
    assert(ZipInstallPath(entries[2], root) == "mod.json");
    assert(ZipInstallPath(entries[3], root) == "mod/data.txt");
    // The directory must be found from the end, and a truncated tail refused.
    assert(!FindZipDirectory(k_zip, 21, size, location));
    std::vector<unsigned char> corrupt(k_zip, k_zip + size);
    corrupt[location.offset] ^= 0xff;
    assert(!ParseZipDirectory(corrupt.data() + location.offset, location.size, location.entries, entries));
}

void TestPaths() {
    assert(SanitizeArchivePath("mods/A/mod.json") == "mods/A/mod.json");
    assert(SanitizeArchivePath("mods\\A\\mod.json") == "mods/A/mod.json");
    assert(SanitizeArchivePath("mods/A/") == "mods/A");
    assert(SanitizeArchivePath("../evil").empty());
    assert(SanitizeArchivePath("mods/../../evil").empty());
    assert(SanitizeArchivePath("/abs").empty());
    assert(SanitizeArchivePath("C:/abs").empty());
    assert(SanitizeArchivePath("a//b").empty());
    assert(SanitizeArchivePath("./a").empty());
    assert(SanitizeArchivePath("").empty());
    assert(SanitizeArchivePath(std::string("a\nb")).empty());
    ZipEntry outside; outside.name = "other/file.txt";
    assert(ZipInstallPath(outside, "pkg/").empty());
}

void TestVerifiedMods() {
    const char* json = R"({
      "nyami.mp_brick": {"Repository": "https://x", "Versions": [
        {"Version": "1.0.1", "Checksum": "aa", "DownloadLink": "https://gcdn.thunderstore.io/live/repository/packages/Nyami11-mp_brick-1.0.1.zip", "Platform": "thunderstore"},
        {"Version": "1.0.2", "Checksum": "bb", "DownloadLink": "https://gcdn.thunderstore.io/live/repository/packages/Nyami11-mp_brick-1.0.2.zip", "Platform": "thunderstore"}
      ]},
      "Apex Weapons Pack": {"Repository": "https://y", "Versions": [
        {"Version": "1.0.2", "Checksum": "cc", "DownloadLink": "https://storage.modworkshop.net/mods/files/55042_x.ApexWeaponPack.zip?filename=ApexWeaponPack.zip", "Platform": "modworkshop"}
      ]}
    })";
    std::vector<VerifiedMod> mods;
    assert(ParseVerifiedMods(json, mods) && mods.size() == 2);
    const VerifiedModVersion* brick = FindVerifiedModVersion(mods, "nyami.mp_brick", "1.0.2");
    assert(brick && brick->checksum == "bb" && brick->platform == VerifiedModPlatform::Thunderstore);
    assert(!FindVerifiedModVersion(mods, "nyami.mp_brick", "9.9.9"));
    assert(!FindVerifiedModVersion(mods, "unknown", "1.0.2"));
    const VerifiedModVersion* apex = FindVerifiedModVersion(mods, "Apex Weapons Pack", "1.0.2");
    assert(apex && apex->platform == VerifiedModPlatform::ModWorkshop);

    assert(ModArchiveName(brick->downloadLink) == "Nyami11-mp_brick-1.0.2.zip");
    assert(ModArchiveName(apex->downloadLink) == "ApexWeaponPack.zip");
    assert(ModInstallFolder("Nyami11-mp_brick-1.0.2.zip", "1.0.2", VerifiedModPlatform::Thunderstore) == "Nyami11-mp_brick-1.0.2");
    assert(ModInstallFolder("ApexWeaponPack.zip", "1.0.2", VerifiedModPlatform::ModWorkshop) == "ApexWeaponPack-1.0.2");
    assert(ModInstallFolder("noext", "1.0.0", VerifiedModPlatform::Thunderstore).empty());
    assert(ModInstallFolder("..zip", "1.0.0", VerifiedModPlatform::Thunderstore).empty());

    // A malformed version rejects the whole list, as on PC.
    assert(!ParseVerifiedMods(R"({"a": {"Repository": "r", "Versions": [{"Version": "1"}]}})", mods));
    assert(!ParseVerifiedMods(R"({"a": {"Versions": []}})", mods));
    assert(ParseVerifiedMods("{}", mods) && mods.empty());
    assert(!ParseVerifiedMods("[]", mods));
}

int CheckArchive(const char* path) {
    FILE* file = std::fopen(path, "rb");
    if (!file) { std::printf("cannot open %s\n", path); return 1; }
    std::vector<unsigned char> data;
    unsigned char buffer[65536];
    std::size_t n;
    while ((n = std::fread(buffer, 1, sizeof(buffer), file)) > 0) data.insert(data.end(), buffer, buffer + n);
    std::fclose(file);
    Sha256 sha;
    sha.Update(data.data(), data.size());
    const std::size_t tail = data.size() < 65557 ? data.size() : 65557;
    ZipDirectoryLocation location;
    std::vector<ZipEntry> entries;
    if (!FindZipDirectory(data.data() + data.size() - tail, tail, data.size(), location) ||
        !ParseZipDirectory(data.data() + location.offset, location.size, location.entries, entries)) {
        std::printf("%s: directory unreadable\n", path);
        return 1;
    }
    std::uint64_t total = 0;
    for (const auto& entry : entries) {
        if (entry.IsDirectory()) continue;
        std::uint64_t offset = 0;
        if (!ZipDataOffset(data.data() + entry.localHeaderOffset, entry, offset)) return 1;
        std::uint32_t crc = 0;
        std::uint64_t size = 0;
        if (entry.method == 0) {
            crc = Crc32Update(0, data.data() + offset, entry.size);
            size = entry.size;
        } else {
            MemorySource source{data.data() + offset, entry.compressedSize};
            CountingSink sink;
            auto inflater = std::make_unique<Inflater<MemorySource, CountingSink>>(source, sink);
            if (inflater->Run() != InflateStatus::Ok) { std::printf("%s: %s failed\n", path, entry.name.c_str()); return 1; }
            crc = inflater->Crc();
            size = inflater->Written();
        }
        if (crc != entry.crc || size != entry.size) { std::printf("%s: %s mismatch\n", path, entry.name.c_str()); return 1; }
        total += size;
    }
    std::printf("%s: %zu entries, %llu bytes, sha256 %s\n", path, entries.size(),
        static_cast<unsigned long long>(total), sha.FinishHex().c_str());
    return 0;
}
} // namespace

int main(int argc, char** argv) {
    TestHashes();
    TestInflate();
    TestZip();
    TestPaths();
    TestVerifiedMods();
    for (int i = 1; i < argc; ++i)
        if (CheckArchive(argv[i])) return 1;
    std::printf("mod_download tests passed\n");
    return 0;
}
